package:
    type:           yii2-extension
    name:           yii2-asset-adminlte
    title:          Yii2 asset for AdminLTE
    headline:       Yii2 AdminLTE
    keywords:       adminlte, asset, extension, yii2
    namespace:      hiqdev\assets\adminlte

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
