parent:
    github:         hiqdev/hidev-config

package:
    name:           yii2-asset-adminlte
    namespace:      hiqdev\assets\adminlte
    title:          Yii 2 asset for bower adminlte
    type:           yii2-extension
    keywords:       adminlte, asset, extension, yii2
    year:           2015

composer.json:
    require:
        yiisoft/yii2:               "~2.0"
        bower-asset/adminlte:       "2.1.1"
    extra:
        asset-installer-paths:
            npm-asset-library:      vendor/npm
            bower-asset-library:    vendor/bower

